# Regla para reenviar las llamadas de la API a tu backend en Google Cloud Run.
[[redirects]]
  from = "/api/*"
  to = "https://applectoescritura-backend-702516870563.europe-west1.run.app/:splat"
  status = 200
  force = true